title: Black-Box Adversarial Defense Against Voice Conversion Using Latent Space Perturbation
description: Submitted to the ICASSP 2025
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
logo: thumbnail.png